blank_issues_enabled: false
contact_links:
  - name: Questions / Help
    url: https://github.com/nicholasgalante/redefinedpipes/discussions
    about: For questions and help, use Discussions instead of Issues
